export type Player = {
    id: number,
    readonly title: string,
    category: string,
    age: number,
    country: string,
    gender: "M" | "F",
    image: string,
    dominantHand: "destra" | "sinistra",
    backhand: "una mano" | "due mani",
    heightCm: number,
    weightKg: number,
    debutYear: number,
    ranking?: number,
    bestRanking: number,
    tourTitles: number,
    bigTitles: number,
    grandSlamTitles: {
        total: number,
        australianOpen: number,
        rolandGarros: number,
        wimbledon: number,
        usOpen: number,
    },
    "1000Titles": number,
    "500Titles": number,
    "250Titles": number,
    finalsTitles: number,
    olympicGolds: number,
    favouriteSurface: ("Cemento" | "Terra rossa" | "Erba")[],
    racket: string,
    shoes: string,
    clothing: string,
    coach?: string[],
    readonly firstNumberOneDate?: string
}